Repository hashicorp/terraform-provider-nomad, pull requests merged in 2018-12, with the labels that each got.

#45 Update job.html.markdown
  website/docs/r/job.html.markdown
Labels: size/XS

#41 Adding datasource for nomad_namespaces resource
  nomad/data_source_namespaces.go
  nomad/data_source_namespaces_test.go
  nomad/provider.go
  website/docs/d/namespaces.html.markdown
  website/nomad.erb
Labels: size/M

#37 clarify the syntax of the Nomad server
  website/docs/index.html.markdown
Labels: documentation, size/XS

#42 Enable json jobs as jobpecs
  nomad/resource_job.go
  nomad/resource_job_test.go
  website/docs/r/job.html.markdown
Labels: documentation, size/M

#48 updated CHANGELOG to reflect new PRs
  CHANGELOG.md
Labels: size/XS

#34 Adding datasource for nomad_deployments resource
  nomad/data_source_deployments.go
  nomad/data_source_deployments_test.go
  nomad/provider.go
  website/docs/d/deployments.html.markdown
  website/nomad.erb
Labels: documentation, enhancement, new-data-source, size/L

#32 Adding datasource for nomad_job resource
  nomad/datasource_nomad_job.go
  nomad/datasource_nomad_job_test.go
  nomad/provider.go
  website/docs/d/job.html.markdown
  website/nomad.erb
Labels: documentation, enhancement, new-data-source, size/XL
