Repository hashicorp/terraform-provider-nomad, pull requests merged in 2019-05, with the labels that each got.

#52 Run `terraform fmt` over the example code in the docs
  website/docs/r/acl_policy.html.markdown
  website/docs/r/acl_token.html.markdown
  website/docs/r/namespace.html.markdown
  website/docs/r/sentinel_policy.html.markdown
Labels: documentation, size/XS

#49 Added quotas to namespaces
  website/docs/r/namespace.html.markdown
Labels: documentation, size/XS

#62 Fix spelling
  website/docs/r/job.html.markdown
Labels: documentation, size/XS

#63 F rich diff merged
  CHANGELOG.md
  GNUmakefile
  go.mod
  nomad/data_source_deployments_test.go
  nomad/datasource_nomad_job_test.go
  nomad/resource_job.go
  nomad/resource_job_test.go
  scripts/start-nomad.sh
  vendor/github.com/pmezard/go-difflib/LICENSE
  vendor/github.com/pmezard/go-difflib/difflib/difflib.go
  vendor/github.com/stretchr/testify/LICENSE
  vendor/github.com/stretchr/testify/assert/assertion_format.go
  vendor/github.com/stretchr/testify/assert/assertion_format.go.tmpl
  vendor/github.com/stretchr/testify/assert/assertion_forward.go
  vendor/github.com/stretchr/testify/assert/assertion_forward.go.tmpl
  vendor/github.com/stretchr/testify/assert/assertions.go
  vendor/github.com/stretchr/testify/assert/doc.go
  vendor/github.com/stretchr/testify/assert/errors.go
  vendor/github.com/stretchr/testify/assert/forward_assertions.go
  vendor/github.com/stretchr/testify/assert/http_assertions.go
  vendor/modules.txt
Labels: dependencies, size/XXL

#64 Monitor job after registration until deployment is complete
  nomad/resource_job.go
  scripts/stop-nomad.sh
  vendor/modules.txt
  website/docs/r/job.html.markdown
Labels: dependencies, documentation, size/L
