Repository hashicorp/terraform-provider-nomad, pull requests merged in 2019-10, with the labels that each got.

#80 add `auto_promote` key on job tests
  nomad/datasource_nomad_job_test.go
  nomad/resource_job_test.go
Labels: size/XS

#81 Support Nomad v0.10.0-rc.1
  go.mod
  go.sum
  nomad/core/README.md
  nomad/core/jobspec/parse_group.go
  nomad/core/jobspec/parse_service.go
  nomad/resource_job.go
  nomad/resource_job_test.go
  vendor/github.com/hashicorp/nomad/api/services.go
  vendor/github.com/hashicorp/nomad/api/tasks.go
  vendor/modules.txt
Labels: dependencies, size/S

#90 Add `create_time` computed value to `nomad_acl_token` resource
  nomad/resource_acl_token.go
  nomad/resource_acl_token_test.go
  website/docs/r/acl_token.html.markdown
Labels: documentation, size/XS

#88 add data source for nomad ACL tokens
  nomad/data_source_acl_token.go
  nomad/data_source_acl_token_test.go
  nomad/provider.go
  website/docs/d/acl_token.html.markdown
  website/nomad.erb
Labels: documentation, size/L

#89 Add Data Source for a Nomad ACL Policy.
  nomad/data_source_acl_policy.go
  nomad/data_source_acl_policy_test.go
  nomad/provider.go
  website/docs/d/acl_policy.html.markdown
  website/nomad.erb
Labels: documentation, size/L
