Repository hashicorp/terraform-provider-nomad, pull requests merged in 2020-07, with the labels that each got.

#122 changelog entry for #121
  CHANGELOG.md
Labels: size/XS

#127 Add purge_on_delete to nomad_job resource
  nomad/resource_job.go
  nomad/resource_job_test.go
  website/docs/r/job.html.markdown
Labels: documentation, size/M

#129 changelog entries
  CHANGELOG.md
Labels: size/XS

#130 renamed nomad_job purge_on_delete to purge_on_destroy
  CHANGELOG.md
  nomad/resource_job.go
  nomad/resource_job_test.go
  website/docs/r/job.html.markdown
Labels: documentation, size/XS

#133 Update plugin.html.markdown
  website/docs/d/plugin.html.markdown
Labels: documentation, size/XS

#131 install and use nomad for testing
  .travis.yml
  scripts/getnomad.sh
  scripts/getvault.sh
Labels: documentation, size/S
