Repository hashicorp/terraform-provider-nomad, pull requests merged in 2020-08, with the labels that each got.

#138 refactor travis testing to not eat failed tests
  nomad/data_source_namespace_test.go
Labels: size/XS

#136 data-source/job_parser: add new data source
  CHANGELOG.md
  nomad/data_source_job_parser.go
  nomad/data_source_job_parser_test.go
  nomad/provider.go
  website/docs/d/job_parser.html.markdown
  website/nomad.erb
Labels: documentation, size/XL

#140 Update Nomad dependency to v0.12.2
  CHANGELOG.md
  go.mod
  go.sum
  nomad/core/jobspec/parse.go
  nomad/core/jobspec/parse_service.go
  nomad/data_source_job_parser_test.go
  nomad/resource_job_test.go
  scripts/getnomad.sh
Labels: size/L

#141 Fix CHANGELOG formatting
  CHANGELOG.md
Labels: size/XS

#142 Fix CHANGELOG entry
  CHANGELOG.md
Labels: size/XS

#143 Prep work to migrate repo
  CHANGELOG.md
  README.md
  go.mod
  main.go
  nomad/core/README.md
  nomad/core/jobspec/parse.go
  nomad/core/jobspec/parse_group.go
  nomad/core/jobspec/parse_job.go
  nomad/core/jobspec/parse_multiregion.go
  nomad/core/jobspec/parse_network.go
  nomad/core/jobspec/parse_service.go
  nomad/core/jobspec/parse_task.go
  nomad/resource_job.go
  nomad/resource_job_test.go
  scripts/changelog-links.sh
Labels: size/M

#147 resource/volume: add "mount_options" argument to volume resource.
  nomad/resource_volume.go
  website/docs/r/volume.html.markdown
Labels: enhancement

#148 changelog: add entry for GH-147
  CHANGELOG.md
Labels: documentation, enhancement
