Repository hashicorp/terraform-provider-nomad, pull requests merged in 2020-06, with the labels that each got.

#114 Explain how to use alias for multi-region clusters
  website/docs/index.html.markdown
Labels: documentation, size/XS

#115 Update examples
  website/docs/d/job.html.markdown
  website/docs/d/regions.html.markdown
  website/docs/index.html.markdown
  website/docs/r/acl_policy.html.markdown
  website/docs/r/acl_token.html.markdown
  website/docs/r/job.html.markdown
  website/docs/r/namespace.html.markdown
Labels: documentation, size/M

#113 deps: updated nomad api client to 0.11.3
  go.mod
  go.sum
Labels: size/XS

#118 error in changelog description
  CHANGELOG.md
Labels: size/XS
