Repository hashicorp/terraform-provider-nomad, pull requests merged in 2021-03, with the labels that each got.

#202 deps: update Nomad API and jobspec deps to 1.0.4.
  go.mod
  go.sum
Labels: theme/dependency, type/enhancement

#204 changelog: add entry for #202
  CHANGELOG.md
Labels: theme/docs, type/enhancement

#211 Allow passing HCL2 variables to job
  nomad/resource_job.go
  nomad/resource_job_test.go
  website/docs/r/job.html.markdown
Labels: theme/docs, theme/resource/job
